language: python

python:
  - 3.6

install:
  - pip install -r .requirements
  - pip install coverage codecov

script:
  - coverage run --source "sugar_router" --module "unittest" discover --verbose "test"
  - coverage report

after_success:
  - codecov --token "41813bfa-0b3c-470a-bfe7-8470a55e472e"

notifications:

  email: false

  slack:

    rooms:
      - sugarush:ZmgII1nbdMZf6FEhq7PgiuAG#travis-ci

    template:
      - "%{repository_name}@%{branch} commit <%{compare_url}|%{commit}> build <%{build_url}|%{result}>"
      - "%{author}: %{commit_message}"

    on_pull_requests: false
